@Api_HostAddress = http://localhost:5166/api

GET {{Api_HostAddress}}/movies
Accept: application/json

###

POST {{Api_HostAddress}}/movies
Content-Type: application/json

{
  "title": "",
  "yearOfRelease": 3200,
  "genres": ["Action", "Sci-Fi"]
}

###
GET {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa

###
PUT {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa
Content-Type: application/json

{
  "title": "Titanic",
  "yearOfRelease": 1997,
  "genres": ["Action", "Sci-Fi"]
}

###
DELETE {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa