@Api_Identity = http://localhost:6000
@Api_HostAddress = http://localhost:5166/api

POST {{Api_Identity}}/token
Accept: application/json
Content-Type: application/json

{
  "userId": "0d76c951-e99c-4752-9417-4209a3f658ab",
  "email": "admin@gurame.com",
  "customClaims": {
    "admin": false,
    "trusted_member": true
  }
}

###
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJqdGkiOiJlNjc0MDY4Yi03Y2JiLTRhOWItOGJhMS1jNzU5YWQxM2FjZTIiLCJzdWIiOiJhZG1pbkBndXJhbWUuY29tIiwiZW1haWwiOiJhZG1pbkBndXJhbWUuY29tIiwidXNlcmlkIjoiMGQ3NmM5NTEtZTk5Yy00NzUyLTk0MTctNDIwOWEzZjY1OGFiIiwiYWRtaW4iOmZhbHNlLCJ0cnVzdGVkX21lbWJlciI6dHJ1ZSwibmJmIjoxNzIyOTc0NDk3LCJleHAiOjE3MjMwMDMyOTcsImlhdCI6MTcyMjk3NDQ5NywiaXNzIjoiaHR0cHM6Ly9pZC5ndXJhbWUuY29tIiwiYXVkIjoiaHR0cHM6Ly9tb3ZpZXMuZ3VyYW1lLmNvbSJ9.BrkT8u2pNrT79aR28YRPZkSjZMW4lvu497gS7dRn2Kw

###
GET {{Api_HostAddress}}/movies?page=1&pageSize=5
Accept: application/json
Authorization: Bearer {{token}}

###

POST {{Api_HostAddress}}/movies
Content-Type: application/json

{
  "title": "",
  "yearOfRelease": 3200,
  "genres": ["Action", "Sci-Fi"]
}

###
GET {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa

###
PUT {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa
Content-Type: application/json

{
  "title": "Titanic",
  "yearOfRelease": 1997,
  "genres": ["Action", "Sci-Fi"]
}

###
DELETE {{Api_HostAddress}}/movies/0d76c951-e99c-4752-9417-4209a3f658aa